### PR TITLE
Merge ceviche repo 🎉

### PR DESCRIPTION
**Pull request by marvinhagemeister**
This PR merges the code from `ceviche` back into the public repo. `ceviche` is our codename for Preact X. An alpha release on npm will follow shortly on March 4th.

Todos:

- [x] Resolve Merge-Conflicts
- [x] Preserve git history of both projects
- [x] Verify changes with `git diff ceviche..ceviche/master`
- [x] Remove 8.x code that's been unaffected by the merge
- [x] Verify TS types, `children` type-checking seems to be broken.
- [x] Fix missing Text-Nodes in `Children` tests.
- [x] Fix missing code coverage in compat.

_Note: The commit view here on GitHub doesn't show all commits. The most recent ones are missing for me in the web ui. They're all there when viewed locally via git._

### CODE REVIEW

**Comment by marvinhagemeister** [comment]
Just went over the changes and pushed 2 minor corrections to our TS types.

We seemed to have missed to enable code coverage for `compat` in our `ceviche` repo, which is why coveralls is failing. I just pushed a few commits adding a lot of tests for `compat`. Something seems to be going on with `Children.map/forEach`. It seems to swallow text nodes. It's unlikely that they are causing it themselves, it's probably something else in compat.

I'm quite busy today. Maybe I can take an hour off to check this evening.

Apart from that I think we're good to go. All other open PRs that we have in the other repo can be done here and be based on master once this PR lands.

**Comment by marvinhagemeister** [comment]
Phew, finally managed to add tests for every missing line that wasn't covered with a test :tada: Everything is green now :+1:

**Comment by developit** [comment]
@marvinhagemeister going above and beyond as always 😁

**Comment by marvinhagemeister** [comment]
@developit No need for it, already found and fixed it :tada: https://github.com/developit/preact/pull/1302/commits/9ab2ea770285cd477315eb5a51d5fa16b1010280

**Comment by thysultan** [comment]
[Minor change 1](https://github.com/developit/preact/blob/f8c09274b9bf3ab4e3618c002bcd87aedc9c834c/CHANGELOG.md#minor-changes) is going to prove hot on the wheels of browsers, at least in comparison to the current implementation, and when hooks land; considering inline-functions will become more common in that space. Is there any reason the previous route was ditched – 1 listener mount + a map of callbacks that are updated?

**Comment by marvinhagemeister** [comment]
@thysultan The changelog isn't really up to date. Event listeners in ceviche work the same way as they do in current preact. That section was written before we implemented them there.

To avoid any further confusion I'll remove it.

**Comment by hassanbazzi** [comment]
So exciting!

**Comment by dyaa** [comment]
Merge time, and let the community celebrate? :shipit: :dancers: :tada:

**Comment by mochiya98** [comment]
Why is not included "compat/*" in package.files?

**Comment by marvinhagemeister** [comment]
@mochiya98 Good catch! Added it :+1:

**Comment by developit** [comment]
aaaaand we're a go

**Comment by dyaa** [comment]
@developit dont forget the npm release :wink:

**Comment by flppv** [comment]
Great job! Waiting for updated docs and release notes 😊

**Comment by webdeb** [comment]
@marvinhagemeister 🎉

**Pull request merged**
