### PR TITLE
add TypeScript typings

### PR DESCRIPTION
**Pull request by kruczy**

### CODE REVIEW

**Comment by developit** [comment]
Build error is just a saucelabs issue, ignore it. Thanks for this!

**Comment by jmarsh999** [comment]
Just a quick issue with the typings definition for linkState.  Currently it is defined to return a void, but in reality it should return a function:  
linkState:(name:string) => (e: Event)=>void;

**Comment by developit** [comment]
Correct! Want to PR?

**Comment by jmarsh999** [comment]
Sure, the PR has been submitted

**Pull request merged**
