### PR TITLE
(feat) - support css grid

### PR DESCRIPTION
**Pull request by JoviDeCroock**
Fixes: #1301

One thing I can't figure out is if I should add the mentioned msGridRow because this is as far as I know a measure to support Internet explorer in css and does not belong in our style object.

Seems like my master was not up to date will remake this sec.

File size diff: +7B

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
On slack I saw someone "complain" about stutter https://codesandbox.io/s/7m0wjvvok6

Should I add this aswell?

**Comment by marvinhagemeister** [comment]
@JoviDeCroock Mh looks like it's not about the variable name `stutter` in particular but more about variables in general. We should be able to skip the `px` normalization for all variables. Let's work on that in a follow-up PR :+1:

**Comment by JoviDeCroock** [comment]
> @JoviDeCroock Mh looks like it's not about the variable name `stutter` in particular but more about variables in general. We should be able to skip the `px` normalization for all variables. Let's work on that in a follow-up PR 👍

Do you mean css variables? How would we make a distinction between those?

**Comment by marvinhagemeister** [comment]
They always start with two leading dashes `--foo`. We could add a check for that in our regex: `^--`

**Pull request merged**
