### PR TITLE
Add umd rollup transpile

### PR DESCRIPTION
**Pull request by egdbear**
#1218

### CODE REVIEW

**Comment by prasad0612** [comment]
Waiting for this change :) 👍

**Comment by egdbear** [comment]
wooo hooo nice!

**Comment by egdbear** [comment]
@developit any info on this?

**Comment by prasad0612** [comment]
@developit Any updates? what is pending here?

**Comment by prasad0612** [comment]
@developit @egdbear 
When I installed preact@8.4.2 lib, I still dont see preact.umd.js file? Anything missing?

**Comment by egdbear** [comment]
@prasad0612 after building package you have it inside `dist/preact.umd.js`
@developit should i make PR and put `browser: dist/preact.umd.js` inside package.json?

**Comment by prasad0612** [comment]
@egdbear preact.umd.js should be available if I just do npm install preact. right?

**Comment by egdbear** [comment]
@prasad0612 i think its still not released as @developit said in last comment
https://github.com/developit/preact/issues/1218

**Comment by ForsakenHarmony** [comment]
Released in v8.5.0, sorry it took this long

**Pull request merged**
