### PR TITLE
clear src= on recycled <img>s

### PR DESCRIPTION
**Pull request by robbiewxyz**
This solves #351.  This will resets the `src` attribute to blank (`''`).  This is because most browsers will keeps displaying old image until the new one has loaded.

I've tested with a few other media-related attributes:  `<video src=>`, `<audio src=>`, and `<object data=>`.  None of them appear to care about previous attribute values.  I have not tested the SVG `<image xlink:href=>` attribute, it might also need a similar workaround.

I've closed my old PR, #353, in order to clean things up a bit with git.

### CODE REVIEW

**Comment by developit** [comment]
@robbiewxyz thanks for rebasing, this is next on my list 😇

**Comment by robbiewxyz** [comment]
Okay, so `<image xlink:href=""/>` also needs this fix.  See [codepen.io/robbiewxyz/pen/ObNbVp](http://codepen.io/robbiewxyz/pen/ObNbVp?editors=0010).  I'll be pushing a fix for this shortly.

**Comment by developit** [comment]
Good to know. I'm actually investigating dropping element recycling, will let you know if that looks likely since it would circumvent these issues.

**Comment by robbiewxyz** [comment]
Hmm... I'd be interested to know what recycling is doing for the DOM performance.  Have you played around with any benchmarks yet?

**Comment by developit** [comment]
Only minimally, not sure if I will try to pull thst into v7 or if its too high risk.

**Comment by robbiewxyz** [comment]
Could we merge this fix as a patch release in the meantime?

**Comment by developit** [comment]
I can definitely merge this into 7.x

**Comment by developit** [comment]
Reason I was waiting was because this is going to end up being whack-a-mole with stateful DOM properties. Ideally we'd just drop recycling if the performance and memory consumption is good enough, then all these issues go away.

**Comment by developit** [comment]
@robbiewxyz think it'd be alright to just pull in the `img` case for the patch release? (in 7.x)  Or are you needing the svg one too

**Comment by robertknight** [comment]
Thank-you for the fix, but DOM Element recycling is being removed entirely in the next release of Preact (v8), which should fix this problem.

**Pull request closed without merging**
