### PR TITLE
Use event capturing for some event types to improve consistency with React

### LINKED ISSUE #266: Event capturing
For the most part it is fine to skip the 3rd argument of `addEventListener` but some event types do not bubble - which creates a dilemma when using event delegation (for example, to avoid passing callbacks down the component tree).

I've created some very simple demos here:
- Vanilla JS http://codepen.io/anon/pen/PzXvVE
- React v15.3.0 http://codepen.io/anon/pen/QEPWNx
- Preact v5.7.0 http://codepen.io/anon/pen/YWrzWG

~~All synthetic events in React bubble (or at least _appear_ to do so) so this can create some incompatibilities when switching to Preact.~~

_UPDATE:_ React explicitly supports capturing by appending `Capture` to the attribute, E.G. `onClick` would become `onClickCapture` https://facebook.github.io/react/docs/events.html#supported-events and certain events are set to capture automatically (inc. focus and blur).

I'm not fully aware of the ramifications that changing [this line](https://github.com/developit/preact/blob/705fbbb749cce0fc0f27a3253d4d89ef4780f30a/src/dom/index.js#L61) would be. Perhaps it may be preferable to check the event type against a capturing whitelist.

I'm happy to help implement any changes, even if it's just a note in the docs 😄

### PR DESCRIPTION
**Pull request by i-like-robots**
Fixes #266

From the spec:

> If true, `useCapture` indicates that the user wishes to initiate capture. After initiating capture, all events of the specified type will be dispatched to the registered `EventListener` before being dispatched to any `EventTargets` beneath them in the tree. Events which are bubbling upward through the tree will not trigger an `EventListener` designated to use capture.

### CODE REVIEW

**Comment by developit** [comment]
Perfect! Thanks for sending this, I'll merge shortly 😊
Build errors are just saucelabs being a baddie, haha.

**Comment by i-like-robots** [comment]
I've asked around and had some input as to why this may be a _bad_ idea in some cases and why a whitelist may be preferable.

**Comment by i-like-robots** [comment]
I've taken a second stab at this, adding a whitelist of events to capture

**Comment by developit** [comment]
Awesome, this actually looks a littler safer to me (avoids changing the existing common usage).  I will probably play around with filesize post-merge, don't mind me 😝 💇

**Comment by i-like-robots** [comment]
No worries. I've updated the original issue with a little more information for posterity.

**Pull request merged**
