### PR TITLE
Set component instance constructor to make it work nicely with react-hot-loader

### PR DESCRIPTION
**Pull request by arqex**
Fixes https://github.com/developit/preact/issues/1007

### CODE REVIEW

**Comment by developit** [comment]
Need to check if there are any performance issues with this technique

**Comment by BlakeTurner** [comment]
@developit any update? I'm making the switch to preact (saves me 44kb gzipped!) and this is one of the final hurdles for me.

**Comment by developit** [comment]
I think we are good to give this a try. Tests are passing and I doubt there'll be a massive performance impact.

**Comment by reznord** [comment]
How about releasing a RC version before we directly go to main release?

**Comment by marvinhagemeister** [comment]
@developit Agree, doesn't seem like this would affect performance.

@reznord Perhaps a simple patch release is enough? Just went through the commit history and it only contains bugfixes and updates to our `README`.

**Comment by developit** [comment]
Ok - did a quick perf test. There is impact - not sure how we proceed:

**Native ES Classes:**


**Babel transpiled classes:**


Bench: https://esbench.com/bench/5abb9bd7f2949800a0f619c1

**Comment by marvinhagemeister** [comment]
Oh no. I merged too quickly I guess :/

**Pull request merged**
