### PR TITLE
WIP: Try to fix failing saucelabs connections

### PR DESCRIPTION
**Pull request by marvinhagemeister**
I can't verify this, because I don't have access to saucelabs. Everything I can find via google points to a mismatch of the id of the tunnel.

Current error message on saucelabs:

```
Your test errored. No active tunnel found for identifier karma1525334797
```

@developit Can you check if this fixes it?

### CODE REVIEW

**Comment by mkxml** [comment]
When did this problem start to happen? Sauce Labs used to work in this repo. Maybe a Sauce Connect bug when dependencies got upgraded...

**Comment by marvinhagemeister** [comment]
@mkxml This problem existed well before I joined the team and updated the dependencies.

**Comment by mkxml** [comment]
OK, perhaps we can create a new branch and change code to run Sauce tests there just to sort these Travis/Sauce problems out without messing with `master`.

Like `sauce-test` branch of something.

Then change `karma.conf.js` to allow Sauce to run in that branch.

I do not have the secret key or setup to test Sauce in my fork.

**Comment by marvinhagemeister** [comment]
@mkxml That's exactly what I was going for. This shouldn't be merged before we can verify that it actually solves our issue with saucelabs.

I'll add an `WIP` prefix to the title to make this more clear.

**Comment by mkxml** [comment]
@marvinhagemeister Ran a test branch with this code ([sauce-test](https://github.com/developit/preact/tree/sauce-test)), with Sauce Labs running on that branch. Seems to have the same problem. Can you check the results on [Travis](https://travis-ci.org/developit/preact/builds/374997810)?

**Comment by marvinhagemeister** [comment]
@mkxml Thanks for trying this out. Seems like it doesn't fix the failing builds. Closing because of that.

**Pull request closed without merging**
