### PR TITLE
Cloning attributes object to avoid mutation in h()

### PR DESCRIPTION
**Pull request by narendrashetty**
This fixes the issue #836 which is caused when using `<a {...obj}>` where Babel transpiles to `h('a', obj)` without cloning the `obj`.

So I now clone the attributes object before any operation is done.

This PR also breaks the test `should render components with props` where it compares the passed props with the component props. Since now it doesn't mutate, the `children` property is still part.

What do you think I should do about it @developit.

### CODE REVIEW

**Comment by developit** [comment]
This is probably ly too much of a performance impact to do in every `h()`. Thinking...

**Comment by narendrashetty** [comment]
@developit That's right. Is it then better to fix this issue from Babel side? Can't think of any better solution for this.

React seems to be cloning the object, that's where I got the idea from.

**Comment by developit** [comment]
I would love to fix it in Babel yeah. It's interesting though, I tend to prefer `<div {...props} />` because I know it avoids a clone, now we'd be changing that semantic.

Perhaps if performance testing reveals this clone is cheap enough in preact, we could merge. The function is already there at least.

**Comment by narendrashetty** [comment]
Having the props mutable may give some weird bugs. Because I would never expect the passed props when changed internally effect the outer value.

I come from the idea that if anything in the props needs to be changed, let the outer component know. May be I am wrong. Let me know what you think.

**Comment by developit** [comment]
That's definitely the correct philosophy, so I can see how props being sometimes mutable is problematic. Just want to make sure we solve it in the right place.

**Comment by hellsan631** [comment]
This is one of the nastiest bugs i've ever encountered. Completely giving up on preact because of this. None of my UI libraries work in production any more.

**Comment by hellsan631** [comment]
This kills a lot of compatibility with newer UI react libraries. Where you would expect them to work, they don't. It also is problematic for using a lot of HOC that really help with productivity.

To note: this seems to happen when using preact-cli, and not when creating an alias on a react project.

Case in point, i use storybook to build UI's with preact, and didn't have any issue inside storybook. But in the preact-cli environment, I am unable to use the components that I built. This caused a lot of frustration.

**Comment by Mitranim** [comment]
Just ran into a bug caused by the props mutation. Found this PR. Would love to help it move along, if possible. Mutating user-defined inputs leads to very surprising behavior and should be avoided.

Perhaps we should clone props only when mutating:

```js
	if (attributes && attributes.children != null) {
		if (!stack.length) stack.push(attributes.children);
                 attributes = extend({}, attributes);
		delete attributes.children;
	}
```

In other words, treat them as immutable, but avoid _needless_ copies.

**Comment by marvinhagemeister** [comment]
The issue that this PR resolves is fixed in Preact X. The test from this PR passes in `master` without any additional changes :+1:

**Pull request closed without merging**
