### PR TITLE
added support for getDefaultProps and default props #59

### PR DESCRIPTION
**Pull request by c58**

### CODE REVIEW

**Comment by developit** [comment]
@c58 Looks good. I might play with this a bit to try to get the filesize down.

**Comment by developit** [comment]
@c58 - looking at this now and I'm confused - preact was already invoking `getDefaultProps()` in the component constructor. Not sure how to resolve the two.

**Comment by c58** [comment]
```javascript
this.props = props || hook(this, 'getDefaultProps') || {};
```
if i understand correctly, it does not merge props, but it should. Also, as mentioned in a React docs, it must be invoked before any instances are created. Invoking it in a constructor is not a good idea.

**Comment by developit** [comment]
lol - you work late! Agreed about avoiding in constructor, so I'm just moving your `setDefaultProps()` call into `setComponentProps()` (it just gets called less often).

**Comment by c58** [comment]
Ok :)

**Comment by developit** [comment]
@c58 Actually, on second look I was confusing the semantics of `getNodeProps()` - the place you had it is definitely the best.  So really we're just moving the cache generation into preact-compat. I shouldn't code before my morning coffee, haha.

**Comment by developit** [comment]
Weird, github never marked this as merged but it's definitely merged...

**Pull request merged**
