### PR TITLE
Added modern node versions to travis ci

### PR DESCRIPTION
**Pull request by amilajack**

### CODE REVIEW

**Comment by developit** [comment]
Apparently jscodeshift is messed up, I'll look into it.

**Comment by amilajack** [comment]
I just updated npm dependencies to the latest version, including babel.

I got almost all the tests to pass except for two of them. Wondering if you know why this is happening.

**Comment by developit** [comment]
Ah - please don't do the babel update in this PR, that's a separate issue (Babel 5 still produces smaller output).

The issue is caused by jscodeshift, they will be doing an bugfix release shortly (discussion [here](https://github.com/facebook/jscodeshift/issues/120) and [here](https://github.com/facebook/jscodeshift/commit/65408864be22e719bb81380a8c04ae8d03857ab8#comments)).

If you want the build to pass, roll back the devDependency updates and just remove the caret from `jscodeshift`:

```js
    "jscodeshift": "0.3.20",
```

**Comment by amilajack** [comment]
Oh my bad. Should have asked before making the PR.

**Comment by amilajack** [comment]
Having trouble reverting this. I will close this PR, re-fork, and make a new PR.

**Pull request closed without merging**
