### PR TITLE
fixed #60 componentWillReceiveProps to be called on rerender

### LINKED ISSUE #60: componentWillReceiveProps called on initial render
In react `componentWillReceiveProps` called only on re-render from parent. In Preact it is called on initial render too. It is a problem for some React components (react-router for example)

### PR DESCRIPTION
**Pull request by c58**
Also i added initial tests for lifecycle methods

### CODE REVIEW

**Comment by developit** [comment]
Awesome! So happy to have more tests for this. I'll merge, is it alright if I bundle this with the 4.0 release? I had some stuff depending on the old behavior so I think we can put this in with the other breaking changes (refs, etc). Let me know :)

**Comment by c58** [comment]
4.0 is ok :) I'm working on #59 now
Also i have some suggestions about code style. I dislike comments like this:
```
/** Some comment about something
 *	@private
 */
```

Can we change it to something more general, like this?
```
/**
 *  Some comment about something
 *  @private
 **/

**Comment by developit** [comment]
@c58 I don't see much of a difference, but I don't mind changing them.  I have some fairly drastic changes on a local branch for 4.0 though, maybe it's better for you to work off that branch?  Will push.

**Comment by c58** [comment]
It would be grate to work on latest version to make easier future merging :)

**Comment by c58** [comment]
Hm, linting isn't passing successfully. All because i'm using spaces instead tabs. Is there any reason to use tabs instead of spaces for indention? There is many conversations about the problem, but in my opinion spaces is better :)

**Comment by developit** [comment]
I just prefer tabs. If you're using one of the popular editors like atom, the is an editor config file that should automatically switch to tabs. I'm definitely a tabs person, so I'd like to keep this using them :P

**Comment by c58** [comment]
Ok, tab person, it is not a problem :) I have installed editorconfig plugin, but it does not translate existing code for a style :(

**Comment by developit** [comment]
I think running `eslint --fix` would do it. Or I use an atom plugin to automatically convert between (I think it's called "convert whitespace").

**Pull request merged**
