### PR TITLE
Add support for componentDidCatch Component method

### PR DESCRIPTION
**Pull request by adamsilverstein**
Amends https://github.com/developit/preact/pull/819 removing these [changes](https://github.com/developit/preact/pull/819/files/b616cc88c012e57a89c5aa4d5afcf567183c0593#diff-86702919356dad82cf58b1e4150288f5L161)  - tests still pass.

### CODE REVIEW

**Comment by developit** [comment]
Do we know what the size hit is here?

**Comment by awinogradov** [comment]
Really want it right now! Can't wait!)

Giffy

**Comment by awinogradov** [comment]
@adamsilverstein @developit do you need help here maybe? Any timings for merge?)

**Comment by ForsakenHarmony** [comment]
Size comparison, possibly perf impact

**Comment by developit** [comment]
Looks like the size impact is an added 107 bytes.  For the utility, I think we can call that justifiable.

Still need to run perf tests against this. Hopefully the try blocks don't cause deopts.

**Comment by marvinhagemeister** [comment]
Fixed the TS conflicts 👍

**Comment by awinogradov** [comment]
@marvinhagemeister looks like not ;)

**Comment by marvinhagemeister** [comment]
@awinogradov I did, but we merged other PRs that changed some things in `preact.d.ts` ;)

**Comment by andrewiggins** [comment]
I've setup the ability to run and compare a custom build of preact in my [js-frameworks-benchmark fork in the `preact-componentDidCatch-keyed` branch](https://github.com/andrewiggins/js-framework-benchmark/tree/preact-componentDidCatch-keyed). Instructions to set it up are in the Readme of that branch.

Below are the results from running the tests with `--count 3` on my laptop. However, my laptop is a work laptop I have to run in VM so it may not be the best for consistent perf testing.

The startup and memory allocations were basically the same.

## Duration in milliseconds ± standard deviation (Slowdown = Duration / Fastest)

<table class="results"><thead><tr><th class="benchname"><a href="#" class="">Name</a></th><th>preact-v8.2.7-keyed</th><th>preact-componentDidCatch-keyed</th></tr></thead><tbody><tr><th class="benchname"><a href="#" class="">create rows</a><div class="rowCount">Duration for creating 1000 rows after the page loaded.</div></th><td style="background-color: rgb(99, 191, 124); color: rgb(0, 0, 0);"><span class="mean">241.0</span><span class="deviation">±53.9</span><br><span class="factor">(1.0)</span></td><td style="background-color: rgb(115, 196, 125); color: rgb(0, 0, 0);"><span class="mean">265.7</span><span class="deviation">±53.9</span><br><span class="factor">(1.1)</span></td></tr><tr><th class="benchname"><a href="#" class="">replace all rows</a><div class="rowCount">Duration for updating all 1000 rows of the table (with 5 warmup iterations).</div></th><td style="background-color: rgb(99, 191, 124); color: rgb(0, 0, 0);"><span class="mean">176.0</span><span class="deviation">±7.8</span><br><span class="factor">(1.0)</span></td><td style="background-color: rgb(124, 198, 125); color: rgb(0, 0, 0);"><span class="mean">204.3</span><span class="deviation">±30.7</span><br><span class="factor">(1.2)</span></td></tr><tr><th class="benchname"><a href="#" class="">partial update</a><div class="rowCount">Time to update the text of every 10th row (with 5 warmup iterations) for a table with 10k rows.</div></th><td style="background-color: rgb(125, 198, 125); color: rgb(0, 0, 0);"><span class="mean">154.0</span><span class="deviation">±37.2</span><br><span class="factor">(1.2)</span></td><td style="background-color: rgb(99, 191, 124); color: rgb(0, 0, 0);"><span class="mean">132.3</span><span class="deviation">±9.7</span><br><span class="factor">(1.0)</span></td></tr><tr><th class="benchname"><a href="#" class="">select row</a><div class="rowCount">Duration to highlight a row in response to a click on the row. (with 5 warmup iterations).</div></th><td style="background-color: rgb(99, 191, 124); color: rgb(0, 0, 0);"><span class="mean">5.3</span><span class="deviation">±1.9</span><br><span class="factor">(1.0)</span></td><td style="background-color: rgb(99, 191, 124); color: rgb(0, 0, 0);"><span class="mean">11.3</span><span class="deviation">±4.9</span><br><span class="factor">(1.0)</span></td></tr><tr><th class="benchname"><a href="#" class="">swap rows</a><div class="rowCount">Time to swap 2 rows on a 1K table. (with 5 warmup iterations).</div></th><td style="background-color: rgb(99, 191, 124); color: rgb(0, 0, 0);"><span class="mean">22.7</span><span class="deviation">±9.5</span><br><span class="factor">(1.0)</span></td><td style="background-color: rgb(124, 198, 125); color: rgb(0, 0, 0);"><span class="mean">26.3</span><span class="deviation">±3.9</span><br><span class="factor">(1.2)</span></td></tr><tr><th class="benchname"><a href="#" class="">remove row</a><div class="rowCount">Duration to remove a row. (with 5 warmup iterations).</div></th><td style="background-color: rgb(99, 191, 124); color: rgb(0, 0, 0);"><span class="mean">58.3</span><span class="deviation">±3.3</span><br><span class="factor">(1.0)</span></td><td style="background-color: rgb(113, 195, 125); color: rgb(0, 0, 0);"><span class="mean">63.7</span><span class="deviation">±8.6</span><br><span class="factor">(1.1)</span></td></tr><tr><th class="benchname"><a href="#" class="">create many rows</a><div class="rowCount">Duration to create 10,000 rows</div></th><td style="background-color: rgb(99, 191, 124); color: rgb(0, 0, 0);"><span class="mean">2,153.0</span><span class="deviation">±26.8</span><br><span class="factor">(1.0)</span></td><td style="background-color: rgb(139, 203, 126); color: rgb(0, 0, 0);"><span class="mean">2,711.0</span><span class="deviation">±678.7</span><br><span class="factor">(1.3)</span></td></tr><tr><th class="benchname"><a href="#" class="">append rows to large table</a><div class="rowCount">Duration for adding 1000 rows on a table of 10,000 rows.</div></th><td style="background-color: rgb(99, 191, 124); color: rgb(0, 0, 0);"><span class="mean">352.3</span><span class="deviation">±51.0</span><br><span class="factor">(1.0)</span></td><td style="background-color: rgb(114, 195, 125); color: rgb(0, 0, 0);"><span class="mean">386.7</span><span class="deviation">±33.1</span><br><span class="factor">(1.1)</span></td></tr><tr><th class="benchname"><a href="#" class="">clear rows</a><div class="rowCount">Duration to clear the table filled with 10.000 rows.</div></th><td style="background-color: rgb(99, 191, 124); color: rgb(0, 0, 0);"><span class="mean">299.7</span><span class="deviation">±23.2</span><br><span class="factor">(1.0)</span></td><td style="background-color: rgb(104, 192, 124); color: rgb(0, 0, 0);"><span class="mean">309.0</span><span class="deviation">±36.5</span><br><span class="factor">(1.0)</span></td></tr><tr><th><a href="#" class="sortKey">slowdown geometric mean</a></th><th style="background-color: rgb(102, 192, 124);">1.02</th><th style="background-color: rgb(114, 195, 125);">1.10</th></tr></tbody></table>

**Comment by andrewiggins** [comment]
Here are some perf run results on a more reliable and powerful machine with sligtly more consistent standard deviations: https://gist.github.com/andrewiggins/19c2a1932a2540d343076434919c541b

**Comment by awinogradov** [comment]
So, @developit are we ready? ;)

**Comment by awinogradov** [comment]
Guys?) Any progress here?

**Comment by ForsakenHarmony** [comment]
We'll probably get a realease with all the recent ts fixes out and then merge this

**Comment by awinogradov** [comment]
Still waiting...

**Comment by adamsilverstein** [comment]
Closing in favor of https://github.com/developit/preact/pull/819 now that activity has resumed there :)

**Pull request closed without merging**
