### PR TITLE
Fix: state is not updated when called setState in componentWillMount 

### PR DESCRIPTION
**Pull request by BengBu-YueZhang**
https://github.com/developit/preact/issues/1461

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
Hey, looks good. Mind adding a test for your scenario?

**Comment by BengBu-YueZhang** [comment]
@JoviDeCroock Thank you, I added unit tests

**Comment by developit** [comment]
Note: #1465 might make this work in a more generic way.

**Comment by BengBu-YueZhang** [comment]
> Note: #1465 might make this work in a more generic way.

Does this pr need close?

**Pull request closed without merging**
