### PR TITLE
fix render test that relies on implementation detail

### PR DESCRIPTION
**Pull request by KevinDoughty**
setState is supposed to be asynchronous but in actuality is not. This pull request removes the reliance on that implementation detail in a single test, test/browser/render.js "should not execute append operation when child is at last".

setState should be fixed in the future

### CODE REVIEW

**Comment by KevinDoughty** [comment]
setState is fixed to be asynchronous with https://github.com/developit/preact/pull/1228, and a related PR is https://github.com/developit/preact/pull/1229

**Comment by KevinDoughty** [comment]
More specifically, this test sets state, then immediately reads it back. Passing requires this to be possible, but it should not be possible and should not pass. Thus I wrapped the remaining code in a setTimeout.

**Comment by developit** [comment]
I'm good with removing reliance on synchronous state from this test.

We'll still need to figure out if we have the option to move away from setting state synchronously, but there's no reason to rely on it in this test.

**Comment by KevinDoughty** [comment]
My first PR ever!
ｷﾀ━━━━｡ﾟ+.ヽ(´∀`*)ﾉ ﾟ+.ﾟ━━━━!!

**Pull request merged**
