### PR TITLE
Add preact-render-to-json

### PR DESCRIPTION
**Pull request by nathancahill**
Useful for Jest snapshot testing Preact/JSX components.

### CODE REVIEW

**Comment by developit** [comment]
Oh wow, thanks for putting that together!  I was wondering - how much did you have to change from preact-render-to-string to get it to output JSON?  Just wondering about repos and that kind of stuff.  Happy to have it though!

**Comment by nathancahill** [comment]
I kept all of the logic and stripped out the JSX and string stuff. Basically returns:

```
{
    type: nodeName,
    props: attributes,
    children: pieces
}
```

**Comment by developit** [comment]
one thing I noticed - we can rip out the encodeEntities entirely, JSON doesn't require HTML entity escapement

**Comment by nathancahill** [comment]
You're right of course. I'll update that.

**Comment by oren** [comment]
Is that the preferred way to test components in Preact? If so this should be part of the official docs. It will be very helpful for beginners to see a good way of testing in Preact.

**Comment by nathancahill** [comment]
Well, I literally created the project/repo a couple hours ago, so "preferred" is relative 🙂

But I did explore the docs looking for a section on testing first, before forking preact-render-to-string to create this project. So it might be good to add a docs section on testing.

**Comment by developit** [comment]
@oren It's for Jest only, but a great solution.  I'd like to include it in preact-boilerplate and potentially preact-cli if it works as well as it looks like it should.

**Comment by oren** [comment]
I understand that it is best only. I would think that having it as part of the official docs is valuable since we currently have nothing about testing.

**Pull request merged**
