### PR TITLE
Fix `this` inside event handlers

### PR DESCRIPTION
**Pull request by leonid-bauxy**
See [this](https://github.com/developit/preact/issues/148#issuecomment-219904671) comment for details.

### CODE REVIEW

**Comment by developit** [comment]
Thanks @le0nik. I'll merge this shortly (I've been on vacation but I'm back tomorrow night) and do a round of testing on a bunch of codebase to ensure nothing breaks.

**Comment by developit** [comment]
Can confirm, your PR is what we should be doing: http://jsfiddle.net/developit/dorupezh/

**Comment by leonid-bauxy** [comment]
@developit Thanks for checking it! Is there anything else I can do to get this merged?

**Comment by developit** [comment]
I will get a beta out this morning.

**Pull request merged**
