### PR TITLE
Fixed type of render function

### PR DESCRIPTION
**Pull request by katyo**
Fix for issue #597

### CODE REVIEW

**Comment by NekR** [comment]
Well, it looks okay, I just don't know why one would render directly into document. Doing that, you won't be able to escape Preact for anything else.

**Comment by developit** [comment]
can still append non-preact nodes, but they might get garbage collected prior to 8.0 yup.

**Comment by NekR** [comment]
@developit it's [`ParentNode`](https://developer.mozilla.org/en/docs/Web/API/ParentNode) interface. It doesn't have `innerHTML` and friends, so `document` doesn't have them too.

**Comment by NekR** [comment]
Anyway. I think this change won't hurt :-)

**Comment by NekR** [comment]
@developit well, they share `Node` interface of course too. It just was split into parts like `Node`, `ParentNode`, `ChildNode`, etc. `Element` implements most of them :-)

**Comment by robertknight** [comment]
I'm not entirely convinced this change is a good idea. At the moment it works but as you noted, `Document` does not implement the `Element` interface so it is possible that Preact might end up trying to do things with the container that are not supported on a non-`Element` object in future. Still it got approval in the linked issue so I'm going to merge it.

**Pull request merged**
