### PR TITLE
Additions and formatting-fixes to JSDoc notes

### PR DESCRIPTION
**Pull request by sangupta**
JSDoc notes have been added and formatting fixes have been made for the following:

* `cloneElement` function
* `h` function
* A few interfaces in `preact` namespace
* `defer` function
* `isSameNodeType` and `isSameNode` methods

### CODE REVIEW

**Comment by developit** [comment]
Awesome! I made a few changes if you want to look things over again - just some spacing stuff to match the existing annotation style, and tweaked a bit of the text.

**Comment by sangupta** [comment]
@developit thanks so much.

**Comment by sangupta** [comment]
Merged latest changes from the mainline.

**Comment by developit** [comment]
Thanks!

**Pull request merged**
