### PR TITLE
Preparation for typescript 2.4

### PR DESCRIPTION
**Pull request by kwoon**
[Typescript Changes](https://blogs.msdn.microsoft.com/typescript/2017/06/12/announcing-typescript-2-4-rc/)

Please read about Week Types.

### CODE REVIEW

**Comment by UnwrittenFun** [comment]
I feel like this further supports #620

**Comment by marvinhagemeister** [comment]
This PR fixes an issue we just stumbled upon at work:

```bash
48  abstract class Component<PropsType, StateType> implements ComponentLifecycle<PropsType, StateType> {
                   ~~~~~~~~~

node_modules/preact/dist/preact.d.ts(48,17): error TS2559: Type 'Component<PropsType, StateType>' has no properties in common with type 'ComponentLifecycle<PropsType, StateType>
```

+1 on merging this PR

**Comment by marvinhagemeister** [comment]
@developit Any chance this might get merged? This makes preact work again with the latest TypeScript version.

**Comment by disintegrator** [comment]
Great stuff! I also wanted a fix TS 2.4 compile error. While this does overcome the weak type overlap compile error, it does result in an unnecessary abstract class. `ComponentLifecycle<P,S>` isn't really an appropriate abstract class to expose to consumers as part of the public API. Furthermore, it is not referred to or extended by any type other than `Component<P,S>`. Perhaps, the more appropriate solution is to place all the lifecycle methods under `Component<P,S>` and then deleting `ComponentLifecycle<P,S>`. What do y'all think?

**Comment by marvinhagemeister** [comment]
That sounds great as well! The `ComponentLifeCycle` interface only has one implementation anyway.

**Comment by valotas** [comment]
Not directly related, but shouldn't the props be of type `PropsType & ComponentProps<this>` for the ComponentLifecycle methods?

**Pull request merged**
