### PR TITLE
make the preact as same as react in shouldComponentUpdate return value

### PR DESCRIPTION
**Pull request by huangming1994**
Hey, l found there is some difference between `React` and `Preact` about `shouldComponentUpdate`.
if you return a value like `''`,`0`,`false`,`NaN`,`undefined` in `React` , they all skip render. but only `false` skip render in `Preact`.

### CODE REVIEW

**Comment by yaodingyd** [comment]
It's intended. See #898.

**Comment by thysultan** [comment]
@yaodingyd Either i'm reading this wrong but i think the comment by @developit in #898 might come of as confusing. The intention seems to be to follow React in the heuristics of `shouldComponentUpdate`, which is appropriately matched by what @huangming1994 has presented.

**Comment by huangming1994** [comment]
@yaodingyd ok, l didn't see the issue. :D

**Comment by developit** [comment]
Do we know what values React supports for this?  If anyone has time to set up a jsfiddle test, that would be useful.  If we're going to change Preact's behavior here, it only makes sense to bring it more in-line with React's.

**Comment by Kanaye** [comment]
As suggested [here](https://jsfiddle.net/s9szt0sf/1/) a jsfiddle.
Looks like react treats everything `truthy` as `true` and everything `falsy` as `false`.
Also react logs a warning `Warning: TestComponent.shouldComponentUpdate(): Returned undefined instead of a boolean value. Make sure to return true or false.` for `undefined` but not for other non boolean values 😕

**Comment by developit** [comment]
What if we changed the check to this?  It'd get us `0, '', false` equalling false:

```js
&& component.shouldComponentUpdate(props, state, context) == false) {
```

**Comment by marvinhagemeister** [comment]
This is fixed in Preact X :tada:

**Pull request closed without merging**
