### PR TITLE
Add *Capture TypeScript type definitions

### PR DESCRIPTION
**Pull request by andybons**
Since properties support `on<Event>Capture` props, support them in TS.

### CODE REVIEW

**Comment by developit** [comment]
Approved! we may want to check if this interacts poorly with the other TS PR.

**Comment by andybons** [comment]
@developit do you mean this one? https://github.com/developit/preact/pull/933

**Comment by developit** [comment]
Yup

**Comment by andybons** [comment]
This and #933 alter different parts of the file that are unrelated.

**Pull request merged**
