### PR TITLE
clear src= on recycled <img>s

### PR DESCRIPTION
**Pull request by robbiewxyz**
Solves #351

### CODE REVIEW

**Comment by developit** [comment]
Wondering if there is a way to make this target Firefox since that's the only browser affected by the src reuse issue.

**Comment by robbiewxyz** [comment]
It looks like it affects my Chrome as well.  You can try it out with [my old codepen](http://codepen.io/robbiewxyz/pen/xEAzLB).

**Comment by developit** [comment]
Ah okay, didn't realize it was in both.

**Comment by robbiewxyz** [comment]
Hey, just bumping this again:  is there a conflict with merging in this bugfix?

**Comment by developit** [comment]
Nope, just on vacation. On my flight home actually!

**Pull request closed without merging**
