### PR TITLE
Fix componentDidUpdate(prevProps, prevState, snapshot)

### PR DESCRIPTION
**Pull request by 38elements**
If `getSnapshotBeforeUpdate()` is not implemented, `snapshot` is `undefined`.

https://reactjs.org/docs/react-component.html#componentdidupdate

### CODE REVIEW

**Comment by andrewiggins** [comment]
@marvinhagemeister Note, this is a new breaking change we should call out in our release notes. Anyone who was depending on the Preact specific behavior of receiving the context as the 3rd argument to `cDU` will now be broken.

**Comment by marvinhagemeister** [comment]
@andrewiggins you're right, didn't saw that. We even had it in the `8.x` release line. Should we revert the merge?

**Comment by 38elements** [comment]
Since this change is breaking change, I think it is necessary that this is described in release note.
Since there is not the description of the third argument in Preact document, I think this behavior is not a feature.
Therefore, I think that it is better not to revert. 
https://preactjs.com/guide/differences-to-react

**Comment by 38elements** [comment]
@andrewiggins @marvinhagemeister 
IMHO
Since this change is breaking change, I think it is necessary that this is described in release note.
Since there is not the description of the third argument in Preact document, I think the behavior is not a feature.
Therefore, I think that it is better not to revert.
https://preactjs.com/guide/differences-to-react

**Pull request merged**
