### PR TITLE
[945] Update boolean attributes to be empty value for consistency

### PR DESCRIPTION
**Pull request by timurista**
## Change boolean attributes to have empty value

In response to #945 
I added an explicit check in case the value === "true" which simply sets attribute to "" which is inline with web standard in moz docs: https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute

> Boolean attributes are considered to be true if they're present on the element at all, regardless of their actual value; as a rule, you should specify the empty string ("") in value (some people use the attribute's name; this works but is non-standard). See the example below for a practical demonstration.

I also updated the test to make sure it renders empt value instead of ="true"

### CODE REVIEW

**Comment by timurista** [comment]
@developit did you want me to still merge this? Which part still needs to be compressed? Are we talking the elseif statement or something else?

**Comment by developit** [comment]
Not sure yet - let's leave it open for a bit, we won't be cutting a release until next week.

**Comment by timurista** [comment]
sure, np 👍  sounds good to me

**Comment by timurista** [comment]
@developit any news on the perf-review?

**Comment by developit** [comment]
I'm concerned that this may cause issues with some DOM Boolean Attributes, but haven't been able to determine if that's likely or not.

**Comment by timurista** [comment]
@developit you want me to close this then?

**Comment by developit** [comment]
no - I want to write some tests around it and was hoping to have time to research the effects. I actually think we should merge this, I just need to be sure of the implications.

**Comment by timurista** [comment]
@developit this is very out of date, you want me to close it?

**Pull request closed without merging**
