### PR TITLE
added opencollective-postinstall

### PR DESCRIPTION
**Pull request by xdamman**
This will show after `npm install preact` or `yarn add preact`

### CODE REVIEW

**Comment by developit** [comment]
Awesome 💃 
Is 40 the optimal height?

**Comment by xdamman** [comment]
Yes, I tried a bunch, feel free to try different sizes / variants: 

    curl "https://opencollective.com/preact/logo.txt?height=40&variant=blocks&reverse=true"

See also docs on https://github.com/opencollective/opencollective-postinstall

**Comment by xdamman** [comment]
FYI, I've added a ` || exit 0` at the end of the `scripts.postinstall` in `package.json` to make sure it doesn't return an error on production where `devDependencies` are not installed (and therefore the scripts `./node_modules/.bin/opencollective-postinstall` doesn't exist). 
The other option would have been to move `opencollective-postinstall` to `dependencies` but I think it's less elegant than this solution.

**Comment by developit** [comment]
Makes sense!

**Comment by xdamman** [comment]
@developit any idea why travis-ci tests didn't pass? How can we restart it? 
Here is the error: 
```
/home/travis/build/developit/preact/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 504 <!DOCTYPE html>
```

```
The command "./node_modules/coveralls/bin/coveralls.js < ./coverage/lcov.info" exited with 1.
cache.2
store build cache
0.01s
24.96schange detected (content changed, file is created, or file is deleted):
/home/travis/build/developit/preact/node_modules/external-editor/example_async.js
/home/travis/build/developit/preact/node_modules/external-editor/example_sync.js
/home/travis/build/developit/preact/node_modules/external-editor/LICENSE
/home/travis/build/developit/preact/node_modules/external-editor/main/errors/CreateFileError.js
/home/travis/build/developit/preact/node_modules/external-editor/main/errors/LaunchEditorError.js
/home/travis/build/developit/preact/node_modules/external-editor/main/errors/ReadFileError.js
/home/travis/build/developit/preact/node_modules/external-editor/main/errors/RemoveFileError.js
/home/travis/build/developit/preact/node_modules/external-editor/main/index.js
/home/travis/build/developit/preact/node_modules/external-editor/node_modules/tmp/lib/tmp.js
/home/travis/build/developit/preact/node_modules/external-editor/node_modules/tmp/LICENSE
/home/travis/build/developit/preact/node_modules/external-editor/node_modules/tmp/package.json
/home/travis/build/devel
...
changes detected, packing new archive
.
.
.
uploading archive
Done. Your build exited with 1.
```

**Comment by developit** [comment]
Travis is having issues today.

**Comment by xdamman** [comment]
Tests passed! 👍 
What's the process from here?

**Comment by developit** [comment]
Now... we merge ;)

**Comment by lukeed** [comment]
Ran the `curl` command listed above & it killed my terminal. I'm in favor of this post-install message, but hoping that behavior isn't a part of the package.

**Comment by xdamman** [comment]
@lukeed 🤔 what terminal are you using? On Windows? Mac? Linux?

**Comment by lukeed** [comment]
@xdamman iTerm2 (3.0.12) on OSX, running `oh-my-zsh`

**Comment by xdamman** [comment]
I made a bunch of changes to make this more reliable. We now have proper test coverage, including on Windows environment.

@developit should I do another PR?

Alternatively, we can also just add directly a line in the post install like we did for Bower: 

    "postinstall": "echo -e \"\nThanks for downloading Preact.\nPlease consider donating to our open collective\n=> https://opencollective.com/preact/donate\n\""

**Comment by developit** [comment]
@xdamman the basic postinstall echo might make a good first test of this. Want to PR it?

**Comment by xdamman** [comment]
Mmmm... it's actually not that pretty because npm shows the command and then executes it: 


So the only way I see to make something more elegant is to add as a dependency a separate executable that will print that message. Either I add it directly to the repo or we add it as a dependency (then we are back to adding "opencollective-postinstall" and that would be your only dependency).



Or, we could add a `DONATE.md` and as a post install `cat DONATE.md`



Any other idea?

**Comment by developit** [comment]
What about something like this?

```js
"postinstall": "npm run -s donate"
"donate": "echo -e \"\nThanks for downloading Preact.\nPlease consider donating to our open collective\n=> https://opencollective.com/preact/donate\n\""
```

**Comment by xdamman** [comment]
That's a great idea! PR here: https://github.com/developit/preact/pull/661

**Pull request closed without merging**
