### PR TITLE
Only save ref from original attributes.

### PR DESCRIPTION
**Pull request by braddunbar**
Since we only use the ref property of `originalAttributes`, we don't need a reference to the whole object.

### CODE REVIEW

**Comment by developit** [comment]
Nice! Looks like this saves a byte :)

I'm actually wondering if we could drop the function type check there, too. That way if someone passes a String ref it'll throw a fairly reasonable error: "ref is not a function"

**Comment by braddunbar** [comment]
> I'm actually wondering if we could drop the function type check there, too.

Seems reasonable to me!

**Comment by braddunbar** [comment]
Updated in ef2eeb90d87b5465a002fdcc32351894d64c869d.

**Comment by developit** [comment]
Woot! Another 2 bytes gone, and now we show a nice error message :)

**Comment by developit** [comment]
Ended up being 3 bytes! 👍

**Pull request merged**
