### PR TITLE
Add browser field inside package.json for umd build

### PR DESCRIPTION
**Pull request by egdbear**

### CODE REVIEW

**Comment by developit** [comment]
@egdbear - think `umd` is the best default here? I'm fine with it, but there's also a smaller version that is designed for browser loading and doesn't support AMD:
https://unpkg.com/preact@8.4.2/dist/preact.min.js

**Comment by egdbear** [comment]
@developit i guess its by common standard to be UMD build on browser field. Tell me if i am wrong :)

**Comment by developit** [comment]
Nah just figured I'd ask haha.

**Comment by ForsakenHarmony** [comment]
Released in v8.5.0, sorry it took this long

**Comment by developit** [comment]
@ForsakenHarmony  I think we may need to revert this. A few bundlers give precedence to `package.umd` over `package.module`, which means we've effectively disabled tree shaking by adding the umd field. Maybe it's fine to just stick with the unpkg field?

**Comment by lukeed** [comment]
Agreed. I've actually been putting ESM inside the `browser` field; since the tooling that listens to that already handle ESM anyway.

**Pull request merged**
