### PR TITLE
Fix: state is not updated when called setState in componentWillReceiveProps

### PR DESCRIPTION
**Pull request by mochiya98**
refs: #1368

### CODE REVIEW

**Comment by mochiya98** [comment]
thanks! 👍

**Comment by developit** [comment]
@mochiya98 my issue ended up actually being different: `componentWillReceiveProps()` was not being called for top-level `render()` calls, and the fix is in #1377. 

Any chance you have a case you can test against that branch?

**Comment by mochiya98** [comment]
probably it is not the same. still fails on that branch.

**Comment by mochiya98** [comment]
ah, sorry. does it means request for add tests for that branch?  
sorry for my poor english.

**Comment by developit** [comment]
Yeah I'm seeing that too. Interesting.

**Pull request merged**
