### PR TITLE
Ignore dangerouslySetInnerHTML during hydration

### PR DESCRIPTION
**Pull request by developit**
This matches React's behavior.
I can't find the issue right now but I will.

### CODE REVIEW

**Comment by marvinhagemeister** [comment]
Looks like we'd need to remove the `should hydrate with dangerouslySetInnerHTML` test.

**Comment by developit** [comment]
Might be worth adding a warning via preact/debug for this too.

**Comment by cristianbote** [comment]
Hey @developit, I updated the test that was failing and I was trying to see if I could add the warning part. But no idea how to detect this case, inside `debug/`. Any pointers?

**Comment by johannesodland** [comment]
Hey @developit

Is the intention to avoid reaplying innerHTML, or is it to strip away the content of VNodes with dangerouslySetInnerHTML?

When using SSR the current solution strips away all content rendered with dangerouslySetInnerHTML during hydration. **This breaks 10.0.0-beta.2 for us**. 

We use dangerouslySetInnerHTML to render content from our CMS (and have been doing so for years). It renders perfectly on the server, but after 10.0.0-beta.2 the content is stripped away during hydration, essentially leaving the application blank.

**Comment by marvinhagemeister** [comment]
@johannesodland Our future approach will to only attach event listeners in hydration and leave the DOM as is. That work is tracked in #1697

**Pull request merged**
