### PR TITLE
Move donation message to scripts

### LINKED ISSUE #803: Can't install when npm is not available
This fd1df721a374e1ed97694cc5e837a08f4dcf5855 actually breaks things. In environments where only `yarn` is present Preact can't be installed.

### PR DESCRIPTION
**Pull request by andrejsm**
This fixes the issue where installation would fail in environments where `npm` is not available.

Fixes #803

### CODE REVIEW

**Comment by andrejsm** [comment]
Please do check if it works under Windows

**Comment by developit** [comment]
Seems like it doesn't work under Win.

**Comment by andrejsm** [comment]
Thanks for checking. I'll then rewrite it to `node` script. Will get to this within a couple of hours.

**Comment by andrejsm** [comment]
Moved from Shell script to Nodejs script. Works on Windows as well.

**Comment by developit** [comment]
Awesome - tested that out locally too and it works well.  Only thing I'd like to see (and I don't mind doing it myself post-merge) is instead of using `./scripts`, put the script in the existing `config/` dir.

**Comment by andrejsm** [comment]
Moved to `config/`

**Comment by developit** [comment]
Works great!

**Pull request merged**
