### PR TITLE
Fix duplicated text nodes issue in IE

### PR DESCRIPTION
**Pull request by mkxml**
Regarding #430.

### CODE REVIEW

**Comment by developit** [comment]
Just some context:  we'll want to make sure we account for the issue solved by the commit that removed this. I can do some digging to figure out what it was:

https://github.com/developit/preact/commit/c5553cefd67c4dc2ad262df2cfcb986114ef15a9

**Comment by mkautzmann** [comment]
Sure, I'm looking for potential breakages from this change in 7.1.0. Simulating SSR and seeing if it breaks the Text node behavior.

**Comment by mkautzmann** [comment]
Specially in IE.

**Comment by mkautzmann** [comment]
OK, I couldn't find problems by manually testing some scenarios in my local env.

Namely root Text Nodes and inner text nodes with hydration. Everything works fine.

I'm not fully aware of the problem that originated the commit you posted though. I know it has something to do with SSR and hydration.

Do you have a specific repro you would like to try to make sure it's working?

I can add a test to stop future regressions to this PR if applicable.

**Comment by developit** [comment]
I'll try to get a repro together tonight!

**Comment by developit** [comment]
Been thinking about this and I can't remember what the original issue was. The only difference between this and the property check would be this will remove externally created text nodes - but I don't really see much of a use case for them anyway.

**Comment by developit** [comment]
@mkautzmann think we should drop the [`[ATTR_KEY]` prop marker](https://github.com/developit/preact/blob/123978c108579f147c49906c31301ad1712926be/src/vdom/diff.js#L95-L96) from Text nodes in this case since the `instanceof` check will always be true?

**Comment by mkautzmann** [comment]
@developit Done, I've been thinking about the hydration lately and it will perform oddly for root text nodes. I hope other developers will understand that behavior.

I tried to make it work with ATTR_KEY on text nodes. No success.

I think we should ship this quick fix and keep an eye on this, fix IE for now and see if we can improve it in the future.

**Comment by mkautzmann** [comment]
I can add a quick test case for root text nodes hydration. Would it help keep track of this?

**Comment by developit** [comment]
Sure. If it's failing on IE we can mark it as flakey and it'll get skipped for the saucelabs tests.

**Comment by mkautzmann** [comment]
@developit Yeah, spent some time trying to make a quick test case but it is flakey in IE, since it is precisely what I want to test I see no point ignoring it.

I guess I don't have a proper test case for this now. Feel free to merge it or not. 

Then `bug/ie` should be green to merge to `master`.

I'm open to any discussion.

Thanks!

**Pull request merged**
