### PR TITLE
Add support for strict mode in TypeScript

### PR DESCRIPTION
**Pull request by marvinhagemeister**
As mentioned in #1030 we lacked support for TypeScripts `strict` mode which is as the name implies less forgiving on mismatched types.

Changes:

- [x] Enable `strict` mode in `tsconfig.json`
- [x] Make props and state generic optional in `Component` interface
- [x] Fix issues related to `strict` mode

### CODE REVIEW

**Comment by mindplay-dk** [comment]
Thanks for jumping on this! 😄 

Why did you change the type parameter to single letters?

IMO that works when you have a singe type `T` and it's use/meaning is obvious from the generic class' name - hiding the meaning of the type-arguments in this case doesn't really help with readability or comprehension.

If I may, I'd suggest using the `T` prefix convention, e.g. `TProps`, `TState`, which is come conventional when you have more than one type argument.

Or just leave it as-is. (Which may actually make more sense in the context of this PR, as it's largely unrelated to the actual changes you're proposing.)

**Comment by marvinhagemeister** [comment]
That was more to align with react typings. They use single characters for generics throughout the whole codebase. In my opinion this makes it easier to read as well, although opinions on that obviously differ.

**Comment by marvinhagemeister** [comment]
TGFM = Total Gay Frat Move (according to the [urban dictionary](https://www.urbandictionary.com/define.php?term=TGFM)) 🤔 😂

**Comment by k1r0s** [comment]
LOOOO

totally messed xd

Looks good for me

image

**Comment by marvinhagemeister** [comment]
@k1r0s No worries, had a good laugh. That's always a good thing to start the week with :)

**Pull request merged**
