### PR TITLE
Fixes non-passing test in original submission

### PR DESCRIPTION
**Pull request by KrofDrakula**
This PR is in response to the broken tests in #279.

### CODE REVIEW

**Comment by developit** [comment]
Hi @KrofDrakula! I think #279 was sort of superceded by #313, which adds a bunch more tests. It'll be released soon!

**Comment by KrofDrakula** [comment]
Ah, I missed that one and assumed this was an unfixed issue. Is there any timeline for 6.1? This is currently a blocking issue for us.

**Comment by developit** [comment]
I had hoped to get it released last night but didn't have time. I will try to publish today.

**Comment by KrofDrakula** [comment]
Oh, that's great! I'd have hoped it would be soon, but not that soon. :D

Much appreciated. I guess we can just close this PR, then.

**Comment by KrofDrakula** [comment]
Just tried the 6.1 release, fixed the issue. Thank you!

**Pull request closed without merging**
