### PR TITLE
Add _depth to mangle.json

### PR DESCRIPTION
**Pull request by 38elements**
This adds `_depth` to `mangle.json`.

https://github.com/developit/preact/blob/1cddbec5be4d11938ba0f430604edf2e2aeddd0d/src/diff/index.js#L151-L153

### CODE REVIEW

**Comment by JoviDeCroock** [comment]
This seems to add 2 bytes to core

**Comment by 38elements** [comment]
Thank you for comment.
I thought this change is necessary to keep consistent property name.
I think this change is unnecessary.

**Comment by marvinhagemeister** [comment]
@38elements Thanks for the PR, you're right that we should add it to our `mangle` file to avoid any potential name clashes of class properties :+1: 

@JoviDeCroock it probably adds 2 bytes because the name is a bit longer than a single char.

**Comment by 38elements** [comment]
Thank you for comment.
Since Changing `__b` is +1B, `__b` is better than `__D`.

**Pull request merged**
